### PR TITLE
Prepare 1.3.0

### PR DESCRIPTION
**Pull request by jonasfj**
Following https://github.com/dart-lang/oauth2/pull/46

### CODE REVIEW

**Review by sigurdm — APPROVED** [review]
LGTM

**Comment by jonasfj** [comment]
@natebosch, @kevmoo, can one of you add me as uploader on this package?
`pub uploader --package oauth2 add jonasfj@google.com`

**Comment by kevmoo** [comment]
> pub uploader --package oauth2 add jonasfj@google.com

Done!

**Comment by jonasfj** [comment]
Thanks, I've published `1.3.0`

**Pull request merged**
